$(document).ready(function(){
    $("#designimg").click(function(){
    $(".design").toggle()
});
$("#developmentimg").click(function(){
    $(".development").toggle()
});
$("#productimg").click(function(){
    $(".product").toggle()
})
$(".wk1").hover(function(){
    $(".appear1").toggle()
})
$(".wk2").hover(function(){
    $(".appear2").toggle()
})
$(".wk3").hover(function(){
    $(".appear3").toggle()
})
$(".wk4").hover(function(){
    $(".appear4").toggle()
})
$(".wk5").hover(function(){
    $(".appear5").toggle()
})
$(".wk6").hover(function(){
    $(".appear6").toggle()
})
$(".wk7").hover(function(){
    $(".appear7").toggle()
})
$(".wk8").hover(function(){
    $(".appear8").toggle()
})
});